version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - 80:8080
  backend:
    build:
      context: ./backend
    restart: unless-stopped
    ports:
      - 9000:9000
  database:
    build:
      context: ./database
    restart: unless-stopped
    ports:
      - 6397:6397
    volumes:
      - "./data/database:/data"