name: Development 
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  Clone-down:
    name: Clone-down-repo
    runs-on: [inst11-dev, ubuntu:latest]
    steps:
      - name: Checkout-repo
        uses: actions/checkout@v2
      - name: Upload-repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Build-backend:
    needs: [Clone-down]
    name: Build-backend
    runs-on: [inst11-dev, ubuntu:latest]
    container:
      image: golang:1.16
    steps:
      - name: Download-repo
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Build
        run: chmod +x ci/build-backend.sh && ci/build-backend.sh
      - name: Upload-repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
      - name: Upload-binary
        uses: actions/upload-artifact@v2
        with:
          name: backend-binary
          path: ./build/backend/app
  Build-frontend:
    needs: [Clone-down]
    name: Build-frontend
    runs-on: [inst11-dev, ubuntu:latest]
    container:
      image: golang:1.16
    steps:
      - name: Download-repo
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Build
        run: chmod +x ci/build-frontend.sh && ci/build-frontend.sh
      - name: Test
        run: chmod +x ci/test-frontend.sh && ci/test-frontend.sh
      - name: Upload-repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
      - name: Upload-binary
        uses: actions/upload-artifact@v2
        with:
          name: frontend-binary
          path: ./build/frontend/app